"""High-level per-turn DP-MultiRAG orchestration.

:func:`run_turn` glues Module 1, 2, 3, and 4 together for a single user
query and returns a structured :class:`TurnResult`. The function is pure
in the sense that it has no I/O side effects; the only mutation is the
in-place update of the ledger object passed in.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from . import evidence as E
from . import generation as G
from . import retrieval as R
from . import ledger as L


@dataclass
class TurnResult:
    """Structured artefacts produced by :func:`run_turn`."""

    q_tilde: str
    selected: List[dict]
    selected_ids: List[str]
    scores: List[float]
    noisy_scores: List[float]
    rel: List[float]
    phi: List[float]
    delta_eps_ret: List[float]
    transformed: List[dict]
    sigma_trans: float
    sufficiency: float
    action: str
    answer: str
    sigma_gen_per_token: List[float]
    n_tokens: int
    delta_eps_gen_per_doc: Dict[str, float]
    alignment_per_doc: Dict[str, float] = field(default_factory=dict)
    re_retrieved: bool = False
    extra: Dict[str, Any] = field(default_factory=dict)


def run_turn(
    *,
    llm,
    raw_q: str,
    history: List,
    docs: List[dict],
    ledger: dict,
    cfg: dict,
    rng: random.Random,
    reference_answer: Optional[str] = None,
    reference_disclosure: float = 1.0,
    enable_re_retrieve: bool = True,
    re_retrieve_factor: float = 1.5,
    max_tokens_gen: int = 60,
    top_k_logprobs: int = 20,
) -> TurnResult:
    """Run one turn of the DP-MultiRAG pipeline.

    Args:
        llm: object exposing ``chat(...)`` and ``next_token_logprobs(...)``.
        raw_q: user query for this turn.
        history: list of ``(query, answer)`` pairs from previous turns.
        docs: knowledge-base documents.
        ledger: ledger created by :func:`ledger.init_ledger`.
        cfg: dict carrying every per-turn hyperparameter:
            ``top_k, gamma, beta, w, alpha, phi_low, phi_high,
             tau_s, tau_b, eps_t_ret, eps_t_trans, eps_t_gen``.
        rng: ``random.Random`` instance used by Gumbel + Gaussian samplers.
        reference_answer: if provided, Module 3 returns this string and
            charges ``Δε^gen ∝ reference_disclosure · ε_t^gen`` instead of
            invoking the LLM through the DP-decoding loop.
        reference_disclosure: scalar in ``[0, 1]`` used together with
            ``reference_answer``.
        enable_re_retrieve: if ``True``, a ``"retrieve"`` decision triggers
            one additional Module 1 call with a widened top-K.
        re_retrieve_factor: multiplier applied to ``cfg["top_k"]`` when
            re-retrieving (rounded to the nearest integer).
        max_tokens_gen: maximum number of tokens generated by Module 3.
        top_k_logprobs: number of candidate tokens requested per step.

    Returns:
        :class:`TurnResult`.
    """
    cfg_ret = {
        "eps_t_ret": cfg["eps_t_ret"],
        "top_k": cfg["top_k"],
        "delta_ret": cfg.get("delta_ret", 1.0),
        "gamma": cfg["gamma"],
        "beta": cfg["beta"],
        "w": cfg["w"],
    }
    cfg_evi = {
        "eps_t_trans": cfg["eps_t_trans"],
        "phi_low": cfg["phi_low"],
        "phi_high": cfg["phi_high"],
    }
    if "span_classifier" in cfg:
        cfg_evi["span_classifier"] = cfg["span_classifier"]

    cfg_gen = {"eps_t_gen": cfg["eps_t_gen"]}
    for key in ("rho_t_gen", "risk_detector", "risk_patterns"):
        if key in cfg:
            cfg_gen[key] = cfg[key]

    re_retrieved = False
    ret = ev_out = None
    sufficiency = 0.0
    action = "abstain"

    max_attempts = 2 if enable_re_retrieve else 1
    for attempt in range(max_attempts):
        attempt_cfg = dict(cfg_ret)
        if attempt > 0:
            attempt_cfg["top_k"] = int(round(cfg["top_k"] * re_retrieve_factor))
            re_retrieved = True

        ret = R.retrieve(llm, raw_q, history, docs, ledger, attempt_cfg, rng)
        ev_out = E.transform_evidence(ret["selected"], ledger, cfg_evi,
                                      ret["phi"], rng)
        sufficiency = E.sufficiency(ret["q_tilde"], ev_out["evidence"], ledger)
        action = E.decide_action(
            sufficiency, ledger,
            [d["id"] for d in ret["selected"]],
            tau_s=cfg["tau_s"], tau_b=cfg["tau_b"],
        )
        if action != "retrieve":
            break

    selected_ids = [d["id"] for d in ret["selected"]]

    if action == "abstain":
        return TurnResult(
            q_tilde=ret["q_tilde"],
            selected=ret["selected"],
            selected_ids=selected_ids,
            scores=ret["scores"],
            noisy_scores=ret["noisy_scores"],
            rel=ret["rel"],
            phi=ret["phi"],
            delta_eps_ret=ret["delta_eps_ret"],
            transformed=ev_out["evidence"],
            sigma_trans=ev_out["sigma"],
            sufficiency=sufficiency,
            action=action,
            answer="I cannot disclose this information.",
            sigma_gen_per_token=[],
            n_tokens=0,
            delta_eps_gen_per_doc={},
            alignment_per_doc={},
            re_retrieved=re_retrieved,
        )

    if reference_answer is not None:
        gen = G.reference_decode(
            answer=reference_answer,
            disclosure=reference_disclosure,
            transformed=ev_out["evidence"],
            ledger=ledger,
            cfg=cfg_gen,
        )
    else:
        gen = G.privacy_decode(
            llm, ret["q_tilde"], ev_out["evidence"], ledger, cfg_gen, rng,
            max_tokens=max_tokens_gen, top_k_logprobs=top_k_logprobs,
        )

    return TurnResult(
        q_tilde=ret["q_tilde"],
        selected=ret["selected"],
        selected_ids=selected_ids,
        scores=ret["scores"],
        noisy_scores=ret["noisy_scores"],
        rel=ret["rel"],
        phi=ret["phi"],
        delta_eps_ret=ret["delta_eps_ret"],
        transformed=ev_out["evidence"],
        sigma_trans=ev_out["sigma"],
        sufficiency=sufficiency,
        action=action,
        answer=gen["answer"],
        sigma_gen_per_token=gen["sigma_per_token"],
        n_tokens=gen["n_tokens"],
        delta_eps_gen_per_doc=gen["delta_eps_gen_per_doc"],
        alignment_per_doc=gen.get("alignment_per_doc", {}),
        re_retrieved=re_retrieved,
    )


def per_turn_budget(eps_global: float,
                    eps_ret_frac: float,
                    eps_trans_frac: float,
                    eps_gen_frac: float,
                    n_turns: int) -> Dict[str, float]:
    """Uniformly split the hierarchical privacy budget across ``n_turns``.

    Returns a dict with ``eps_t_ret / eps_t_trans / eps_t_gen``.
    """
    n = max(1, n_turns)
    return {
        "eps_t_ret": eps_global * eps_ret_frac / n,
        "eps_t_trans": eps_global * eps_trans_frac / n,
        "eps_t_gen": eps_global * eps_gen_frac / n,
    }
